log:
  # Path for log files, relative to the project root or running directory.
  path: logs
  # Filename for the log, excluding the file extension (which is fixed as .log).
  file: app1
  # Level: Logs at this level or higher will be output (critical==fatal > error > warning==warn > info > debug > notset).
  level: info
  # Format string for log messages.
  fmt: '%(asctime)s %(levelname)s %(module)s.py, line %(lineno)d - %(message)s'
  # Interval for log rotation (e.g., 'S'econds, 'M'inutes, 'H'ours, 'D'ays, 'midnight').
  when: midnight
  # Number of backup log files to retain.
  bak-count: 30
  # Compression level, 0-9, where 0 means no compression.
  compress-level: 9
  # Suffix for the compressed log archives (e.g., .7z, .zip).
  compress-suffix: .7z
  # Cron expression for the scheduled log compression task.
  compress-schedule-cron: 0 1 * * *
  # Number of compressed backup archives to retain.
  compress-bak-count: 90
