log:
  # Path, relative to the directory of the running file
  path: log
  # Filename, excluding the file extension, which is fixed as .log
  file: example
  # Level, logs at this level or higher will be output: critical > error > warning > info > debug > notset
  level: info
  # Compression level, 0-9, where 0 means no compression
  compress-level: 9
